### ISSUE TITLE
Sorry for asking but...

### ISSUE THREAD

**Issue by lAlexiel** [Macck209/Fishing101#2]
Is this a datapack or this mod is not compiled yet? I can't manage to make this mod work, i put in /mods folder and nothing happen... But in downloads on modrinth is only on .zip and not .jar... Sry i'm new on this and i don't know other way to ask you for help

**Comment by Macck209** [comment]
First of all, did you put the mod into your server files or player files? It's server-side, meaning it will only work on servers. 
Second: this mod uses something called [Polymer library](https://github.com/Patbox/polymer) - maybe the mod works, but the textures dont load in? Try `/polymer generate-pack` - this will generate the resource pack with the textures which you can use locally (send it to players/set up an auto-download when players join your server). You can also check with `/give @p fishing101:sushi` if the mod compiled and if the textures work.
Zip is basically the same as .jar so this shouldnt be the issue. 
Let me know if any of this worked and have a nice day!

**Comment by Ricoware** [comment]
You have not provided a mod, you have only provided a zip of the source code.  You cannot just put a zip file with source code in the mods folder of a server and expect anything to happen.  The source code has to be compiled, and the resulting jar file is what is put in the server's mod folder.

**Comment by Ricoware** [comment]
@Macck209 I'm not sure why you liked my post.  What I'm saying is that **_you_** need to compile your mod, and upload the compiled jar to Modrinth/Curse and here as a release, instead of expecting people who want to use your mod to compile it themselves.

**Comment by Macck209** [comment]
@Ricoware Yeah, sorry about that. I've got what you were saying and I'm really thankful for pointing out my mistake (imagine if nobody told me this - How many more people would get confused!). Haven't had the time to fix this yet tho. Will probably do it later today. Thanks again and sorry @lAlexiel for providing an unfinished project :C

**Comment by Macck209** [comment]
@lAlexiel Should work now, just download the new version from modrinth.

**Comment by Ricoware** [comment]
Nice, it's good to have everyone on the same page.  :)  I've downloaded the jar and I'm currently testing it on my private server.  So far, so good!

**Comment by lAlexiel** [comment]
@Macck209 Tysm ♥

**Comment by Macck209** [comment]
All right! I'm gonna close this issue. If anything else comes up, just open another one. Thanks!
