### ISSUE TITLE
[Fabric 1.20.1] All fish except fish bones have same look (and chicken?)

### ISSUE THREAD

**Issue by Dumpling00** [Macck209/Fishing101#8]
Big fan of the concept, but for some reason the items look like this while in inventory. (They look fine in-hand)
This even after generating packs.
Please help?

![image](https://github.com/Macck209/Fishing101/assets/44829013/fb650b69-2628-40d7-b58d-729bb262aee0)

**Comment by Macck209** [comment]
Hello,
That's weird.

Are you playing on a server or on singleplayer? If on a server, did you make sure to apply the resource pack after generating it? Also, what minecraft version are you on?

I'll look into that. Thanks for letting me know.

**Comment by Macck209** [comment]
> Big fan of the concept, but for some reason the items look like this while in inventory. (They look fine in-hand)
> This even after generating packs.
> Please help?
> 
> ![image](https://github.com/Macck209/Fishing101/assets/44829013/fb650b69-2628-40d7-b58d-729bb262aee0)
> 

Moreover, what is the other fishing mod on the screenshot? Maybe its compatibility issue

**Comment by Dumpling00** [comment]
Hi, sorry! I'm on Fabric, 1.20.1, singleplayer. The other fishishing related things in the screenshot, the first row up to the fish bones are all vanilla items and fro the burger onwards, which is from better mcdonalds foods, the rest are simply decorative items from chipped and handcrafted.
Hope this helps!

**Comment by Macck209** [comment]
There seems to be an issue with multiple resource packs interactions. Your other resource pack is overriding tropical fish's texture (and chicken). I'll check whether it's something on my end. 
In the meantime, try putting `Polymer Resources` to the top of resource packs list. That shuld fix it.
![rs1](https://github.com/Macck209/Fishing101/assets/99656897/21e7695a-6155-4e07-909d-0bc9daa10ce6)

**Comment by Dumpling00** [comment]
Hi again, thanks for the tip! I've tried it again and, nope, nothing. :(

**Comment by Macck209** [comment]
Ok, I'll try to fix it in a few days

**Comment by Macck209** [comment]
You can try one more thing - download the latest, updated version of the mod from Modrinth. It should work, but at this point I'm not entirely sure. Thanks for patience - in advance.

**Comment by Dumpling00** [comment]
Hello again! Thank you for your time on this!
I've downloaded the newest version, generated packs again, moved pack in the resource list making sure it stays at the top, and still nothing, unfortunately.
Not going to lie, this is a bit convoluted, I don't understand why there's a need for this extra step when other mods load their textures without issues, is there any particular reason as to why Fishing 101 does it this way?

I have tried making a new blank instance with just Fishing 101 and its dependency, generate pack, and it does work, so I can confirm it's not an underlying issue with the mod itself rather some compatibility issue as first thought.

The only issue now is narrowing it down to the other mod or resource pack that causes this, since my minecraft is HEAVILY loaded lol.

I'm guessing there's really no easy fix to this?

**Comment by Dumpling00** [comment]
I did some educated guessing and - that was actually easy enough to figure out!

So the culprit is apparently the mod "Eating Animations" which reverts your foods to the vanilla look when in inventory.
I'll remove Eating Animations from my list of mods because I'd enjoy playing with your fishing and foods variety much more (plus I have a lot of other modded foods so Eating Animations only really works with the vanilla ones).

Even so, I guess the fact that Eating Animations breaks your food textures is something worth knowing, since the Eating Animations mod is pretty popular, fixing the compatibility issue would be a good thing I reckon.
Most people would just assume Fishing 101 doesn't work and not bother - But they'd be missing out!

Anyway thanks for your time and patience! Keep rocking!

**Comment by Macck209** [comment]
Hi again! Glad you were able to figure it out. I'll make sure to check for compatibility errors with the `Eating Animations` mod.

`Fishing101` behaves differently to other mods. It relies on a special library that allows the mod to work on multiplayer servers without the need for players to download it (hence the resourcepack).

Thanks for the kind words! I'm glad you're enjoing my mod!
Have a good time!
